name: Deploy Vibez to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files to server and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          key: ${{ secrets.VPS_VIBEZ_KEY }}
          script: |
            cd /root/vibez
            git pull origin main

            npm install

            npm run build

            rm -rf /var/www/vibez/*
            cp -r dist/* /var/www/vibez/

            chown -R www-data:www-data /var/www/vibez
            systemctl restart nginx
